// Slug → target. Slugs are opaque random strings, but NOT secret: teams shouting hiding places
// at each other is the goal. Generated by the QR inventory script (see the "QR inventory and
// generator script" ticket).
//
//   'k7f2qx': { game: 'yarn' }              unlock this game and open it
//   'm3p8zz': { game: 'lights', step: 1 }   a hunt step, 1-based
//   'b4xk7m': { page: 'rickroll' }          a pure gag: no game, no points
//
// Every hunt step must have exactly one slug or content validation fails at boot.

// PROTOTYPE FIXTURE — throwaway slugs for the animation-choreography prototype only. The real
// inventory is populated once the roster locks. Delete with the branch.
export default {
  k7f2qx: { game: 'yarn' },
  w9d4tn: { game: 'snaps' },

  m3p8zz: { game: 'lights', step: 1 },
  r6h1vb: { game: 'lights', step: 2 },
  z2c5jq: { game: 'lights', step: 3 },

  b4xk7m: { page: 'too-soon' },
};
